package com.charliechiang.wastesortinghelperserver.config;

public enum Schools {
    SCHOOL_OF_INFORMATION_AND_COMMUNICATION_ENGINEERING,
    SCHOOL_OF_ELECTRONIC_ENGINEERING,
    SCHOOL_OF_COMPUTER_SCIENCE,
    SCHOOL_OF_AUTOMATION,
    SCHOOL_OF_SOFTWARE_ENGINEERING,
    SCHOOL_OF_DIGITAL_MEDIA_AND_DESIGN_ARTS,
    SCHOOL_OF_SCIENCES,
    SCHOOL_OF_ECONOMICS_AND_MANAGEMENT,
    SCHOOL_OF_HUMANITIES,
    SCHOOL_OF_PUBLIC_MANAGEMENT,
    INTERNATIONAL_SCHOOL,
    SCHOOL_OF_E_LEARNING_CONTINUING_EDUCATION,
    SCHOOL_OF_ETHNIC_MINORITY_EDUCATION,
    TEACHING_AND_RESEARCH_CENTER_OF_MARXISM,
    INSTITUTE_OF_NETWORK_TECHNOLOGY,
    INSTITUTE_OF_INFORMATION_PHOTONICS_AND_OPTICAL_COMMUNICATIONS,
    INSTITUTE_OF_PERCEPTION_TECHNOLOGY_AND_INDUSTRY
}
